name: Continious Integration

on:
  pull_request:
    branches:
      - main
jobs:
  unit_tests_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd client
      - run: npm ci
      - run: npm test
      - run: npm run build
